### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by Theodlz** [MickaelRigault/pysedm#16]
Hi!

We're working on integrating pysedm in [SkyPortal](https://github.com/skyportal/skyportal).
We noticed that with recent versions of iminuit and/or watchdog, pysedm breaks. it would be nice to provide a requirements.txt file, where the most recent versions of the packages required by pysedm are pinned.

Thanks!

**Comment by MickaelRigault** [comment]
Will do !

**Comment by Theodlz** [comment]
Thanks! Then, maybe you can do like other packages on pypi, which is enforce that these required packages are downloaded as well when installing pysedm, and will throw and error if whatever app has pysedm in its requirements has pinned an incorrect version of its dependencies.

**Comment by Theodlz** [comment]
Let me know if you need help for that part (after you've defined the requirements)  I'll be happy to help.

**Comment by mcoughlin** [comment]
@MickaelRigault the iminuit stuff in particular yields conflicts with recent sncosmo fits, for example. Is there a timescale to see this resolved?

**Comment by MickaelRigault** [comment]
So @mcoughlin @Theodlz I added the basic requirements. 
However, it will be hard for me to commit time to pysedm right now. I have lots of other things on my plate and having pysedm on SkyPortal, while it is a great idea, is not something I can contribute on. 

for what matters for you, iminuit is important for the PSF fitting, so I believe it is a psfcube problem to solve. 

You are not recreating the 3D cube are you ?

**Comment by mcoughlin** [comment]
@MickaelRigault Makes sense. Is there a small example with https://github.com/MickaelRigault/psfcube that if we get it running we consider it a success? Then me or @Theodlz  can presumably make whatever API change is necessary and knock it out.

**Comment by MickaelRigault** [comment]
@Theodlz Modefit PR done

**Comment by Theodlz** [comment]
Hi @MickaelRigault. Thanks for merging the PR. Please let me know when you do a pypi release so I can open the psfcube PR that pins it along with some other modifications.

**Comment by MickaelRigault** [comment]
Ah, of course. @Theodlz Done. Modefit version 0.4.0 is now online

**Comment by Theodlz** [comment]
Here is the psfcube one @MickaelRigault :rocket: 
https://github.com/MickaelRigault/psfcube/pull/3

**Comment by Theodlz** [comment]
The pysdem one is ready. However, I haven't had the chance to try one method that I modified according to iminuit's new changes, in `astrometry.py`. In general, a lot of methods from this file had incorrect var names and couldn't work, so I'm not sure it was maintained and functional anyway.

Here is the thing that I couldn't test:
```
guesses = self.get_initial_guess(**guess_prop)
boundaries = self.get_boundaries(**boundaries_prop)
fiterr = self.get_fiterror(**error_prop)
fixed = self.get_fixed(**fixed_prop)
```
should each return a dict with the input (of the model) as the key, and the input value, limits, errors, and fixed as the values. The best example of that is the code in psfcube that I just added in the PR mentioned above. Also 2 packages that you import are actually not on pypi, so that couldn't work either.

Here is the pysedm PR for you to review: https://github.com/MickaelRigault/pysedm/pull/17

**Comment by MickaelRigault** [comment]
psfcube merge.
psfcube-0.10.0 online

**Comment by MickaelRigault** [comment]
pysedm-0.31.0 merged and online

Thanks a lot @Theodlz  !

**Comment by MickaelRigault** [comment]
closing the issue. Reopen if bugy
