### ISSUE TITLE
BUNIT header keyword must reflect calibration

### ISSUE THREAD

**Issue by scizen9** [MickaelRigault/pysedm#5]
We need to change the BUNIT keyword in the output spectrum after flux calibration.  It still says ‘electron’, when it should say ‘Flam’ or ‘erg/s/cm^2/A’.

**Comment by MickaelRigault** [comment]
Done.

There now is a BUNIT entry in the header which is:
- `"erg/s/A/cm^2"` if the spectrum is flux calibrated
- gets the original BUNIT if not flux calibrated (or set `""` is none)
