### ISSUE TITLE
Set REDUCER keyword in extract_star.py

### ISSUE THREAD

**Issue by scizen9** [MickaelRigault/pysedm#6]
When re-extraction is performed, this keyword should either be set from the env var SEDM_USER or prompted for.

**Comment by MickaelRigault** [comment]
Done:
There is an keywork entry in the spectrum header called "REDUCER" which is set to be the global variable `$SEDM_USER` or "auto" if no  `$SEDM_USER` is found. 

You can manually set the reducer (which will then ignore `$SEDM_USER`) when running extract_star:
`extract_star.py DATE --auto FILEID --reducer YOUR_NAME`

Note: this does not change `$SEDM_USER`. It just bypass it.
